// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJum6-iQvBs2Ika25WS2-axpS_D6k3TmQ',
    appId: '1:783274114460:web:ba121562e41b6c4b135c59',
    messagingSenderId: '783274114460',
    projectId: 'comments-3ac93',
    authDomain: 'comments-3ac93.firebaseapp.com',
    storageBucket: 'comments-3ac93.appspot.com',
    measurementId: 'G-P33FFTBH3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTj0lotseiKpJQafpMVA5g2O8H-_B3DHQ',
    appId: '1:783274114460:android:53cace7ccbf3acdf135c59',
    messagingSenderId: '783274114460',
    projectId: 'comments-3ac93',
    storageBucket: 'comments-3ac93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiCKS9n78ayGts7ZdmztCwAtJYmmJZXvk',
    appId: '1:783274114460:ios:e7d72145944c360e135c59',
    messagingSenderId: '783274114460',
    projectId: 'comments-3ac93',
    storageBucket: 'comments-3ac93.appspot.com',
    iosBundleId: 'com.dev.comments',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiCKS9n78ayGts7ZdmztCwAtJYmmJZXvk',
    appId: '1:783274114460:ios:e7d72145944c360e135c59',
    messagingSenderId: '783274114460',
    projectId: 'comments-3ac93',
    storageBucket: 'comments-3ac93.appspot.com',
    iosBundleId: 'com.dev.comments',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJum6-iQvBs2Ika25WS2-axpS_D6k3TmQ',
    appId: '1:783274114460:web:751e5fa3326947a0135c59',
    messagingSenderId: '783274114460',
    projectId: 'comments-3ac93',
    authDomain: 'comments-3ac93.firebaseapp.com',
    storageBucket: 'comments-3ac93.appspot.com',
    measurementId: 'G-60RZ665RZ0',
  );
}
